# Generated by Django 5.2.5 on 2025-10-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='task_submissions/'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='submission_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
