# Generated by Django 5.2.5 on 2025-11-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_tasks_submission_file_tasks_submission_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('review', 'In Review'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='todo', max_length=20),
        ),
    ]
