# Generated by Django 5.2.5 on 2025-10-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'HR'), (2, 'Project Manager'), (3, 'Team Lead'), (4, 'Employee'), (5, 'Admin')], db_index=True, default=4),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
    ]
