# Generated by Django 5.2.5 on 2025-10-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_department_name_alter_employee_date_of_joining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_status',
        ),
        migrations.DeleteModel(
            name='EmployeeStatus',
        ),
    ]
