# Generated by Django 5.2.5 on 2025-10-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=10),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
