# Generated by Django 5.2.5 on 2025-10-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_status_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employeeschedule',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='workinghour',
            name='is_active',
        ),
    ]
