# Generated by Django 5.2.5 on 2025-11-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employee_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='working_end_time',
            field=models.TimeField(default='17:00', verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='department',
            name='working_start_time',
            field=models.TimeField(default='09:00', verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
