# Generated by Django 5.2.5 on 2025-11-03 09:35

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_workinghour_employee_workinghour_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghour',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='workinghour',
            name='days_of_week',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], default=['monday', 'tuesday', 'wednesday', 'thursday', 'friday'], max_length=56),
        ),
    ]
