# Generated by Django 5.2.5 on 2025-11-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_remove_workinghour_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_reason',
            field=models.TextField(max_length=255),
        ),
    ]
