# Generated by Django 5.2.5 on 2025-11-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_leave_approved_at_leave_approved_by_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedule',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('on_leave', 'On Leave'), ('off_shift', 'Off Shift')], default='available', max_length=20),
        ),
    ]
